### ISSUE TITLE
Merling Text Description is going skrrt skrrt vroom vroom brt boom

### ISSUE THREAD

**Issue by OzelotAnimations** [ChromexUnderscore/OriginsTweaks#25]
**Describe the bug**
Desription text for one of Merling's abilities is not working properly.

**To Reproduce**
1. Open a world for the first time or use an Origin Orb
2. Go to 'Merling'
3. Scroll down to the ability which is looking wierd
4. See error :)

**Expected behavior**
It shoulda just printed the right text instead of a bunch of string codes.

**Screenshots**
![Screenshot_Minecraft_OriginsTweaks_Merling_AAAA](https://user-images.githubusercontent.com/108491372/176765005-61e878f9-c186-4c38-9ba0-31568a8733c4.png)

**Versions**

+ Windows (10)
+ Minecraft 1.19
+ Fabric Loader 1.19
+ Origins Mod 1.19
+ Pehkui 1.19
+ Fabric API 1.19
+ OriginsTweaks 1.11.0

**Comment by ChromexUnderscore** [comment]
Yeah, I forgot to add a name and description lmao
