### ISSUE TITLE
Trident damage underwater is way too high (Merling)

### ISSUE THREAD

**Issue by OzelotAnimations** [ChromexUnderscore/OriginsTweaks#26]
**Describe the bug**
Attacking mobs with a trident underwater deals more than 100% extra damage, while the ability (Aquadynamic) is said to only deal an extra 50%. I tried this with a husk (Died in 3 hits on land, but only 1 hit underwater) and with an Iron Golem (died in 12 hits on land and only 5 hits underwater)

**To Reproduce**
1. Pick the origin 'Merling' and get yourself a trident
2. Attack something with a trident on land, then a new creature of the same type, underwater
4. The creature should die more than double as quickly underwater (Don't use creatures which can drown btw)
5. See error

**Expected behavior**
I expected the mob to die 50% faster, instead it died more than double as fast.

**Versions**
Please also submit your Software Versions, such as:

+ Windows (10)
+ Minecraft 1.19
+ Fabric Loader 1.19
+ Origins Mod 1.19
+ Pehkui 1.19
+ Fabric API 1.19
+ OriginsTweaks 1.11.0

**Comment by ChromexUnderscore** [comment]
I think I already know why, I probably chose ```multiply_base`` instead of ```multiply_total```, which causes it to add 150%, and not set it to 150%.
I'll fix that then.

**Comment by ChromexUnderscore** [comment]
Fixed in Version 1.11.1
