### ISSUE TITLE
Recipe Config

### ISSUE THREAD

**Issue by Zunwolf1896** [ChromexUnderscore/OriginsTweaks#27]
**Type of Idea**
A way to remove the Origin Orb recipe

**Describe your Idea**
Either add a config where we can disable the origin orb or provide a custom datapack to turn it off.

**Note**
Some Feature Ideas might not get implemented, because they are either not well balanced, hard to implement or the Origin already has enough Buffs

**Comment by ChromexUnderscore** [comment]
I'll look into that once I'm back from vacation.

**Comment by ChromexUnderscore** [comment]
I will look into it, but for now you may want to use this mod:
[Recipe Disabler](https://modrinth.com/mod/recipedisabler/version/1.2.0)

**Comment by ChromexUnderscore** [comment]
Disable Orb of Origins recipe in the ``origins_server.json`` file:
```json
{
  "performVersionCheck": true,
  "origins": {
    "origins:human": {
      "enabled": true,
      "origins:orb": true
    }
  }
}
```

**Comment by ChromexUnderscore** [comment]
Disable Orb of Origins recipe in the ``origins_server.json`` file:
```json
{
  "performVersionCheck": true,
  "origins": {
    "origins:human": {
      "enabled": true,
      "origins:orb": true
    }
  }
}
```
