### ISSUE TITLE
Blazing touch not consuming revving resource

### ISSUE THREAD

**Issue by Chargoal** [ChromexUnderscore/OriginsTweaks#29]
![image](https://user-images.githubusercontent.com/62655322/189739612-932c518c-dba3-4ac0-9ba4-acf39cdc8dd2.png)
In the image above (it's a code of data/originstweaks/powers/blazing_touch.json) it seems that fire aspect of Blazing Touch in revved state is expected to consume some of revved_up_resource. I tested it a couple of times and it 100% doesn't work - the only thing that depletes revved_up_resource is time (originally 128 charges, depleted every second) and not revved Blazing Touch.
It's a little detail I wouldn't know without seeing the code. It's an amazing balance feature, IMHO. I'd love to have it in the mod, and if it's just a dead code, that's not expected to stay there - I'd love to know how to implement it myself then.

**Comment by ChromexUnderscore** [comment]
> ![image](https://user-images.githubusercontent.com/62655322/189739612-932c518c-dba3-4ac0-9ba4-acf39cdc8dd2.png)
> In the image above (it's a code of data/originstweaks/powers/blazing_touch.json) it seems that fire aspect of Blazing Touch in revved state is expected to consume some of revved_up_resource. I tested it a couple of times and it 100% doesn't work - the only thing that depletes revved_up_resource is time (originally 128 charges, depleted every second) and not revved Blazing Touch.
> It's a little detail I wouldn't know without seeing the code. It's an amazing balance feature, IMHO. I'd love to have it in the mod, and if it's just a dead code, that's not expected to stay there - I'd love to know how to implement it myself then. 
> 

It was a feature and worked at some point, but it seems like origins mod had some changes that broke this (or I'm just stupid and broke it myself on accident)
I'll look into this, thank you for sharing!
