### ISSUE TITLE
Phantom has 10 hearts

### ISSUE THREAD

**Issue by Chargoal** [ChromexUnderscore/OriginsTweaks#30]
Origins' Phantom has "Fragile" power, which drops its hp to 7 hearts from vanilla 10 hearts
Originstweaks' phantom.json has no fragile power written and so Phantom has 10 hearts which is not intended by Originstweaks as far as I can tell

**Comment by ChromexUnderscore** [comment]
> Origins' Phantom has "Fragile" power, which drops its hp to 7 hearts from vanilla 10 hearts
> Originstweaks' phantom.json has no fragile power written and so Phantom has 10 hearts which is not intended by Originstweaks as far as I can tell

That is intended to balance out the debuffs inflicted by gold, but thanks for reporting this!
