### ISSUE TITLE
Infinite Reflexes

### ISSUE THREAD

**Issue by Igno-miny** [ChromexUnderscore/OriginsTweaks#32]
**Describe the bug**
The "Reflex" power on the enderian seems to not trigger it's cooldown in server situations.

**To Reproduce**
1. Enter a server.
2. Get shot at by anything that can wield a bow.
3. Ignore the arrow entirely.

**Expected behavior**
The "Reflex" Power is supposed to go on a cooldown, not _permanently_ defend you.

**Screenshots**

**Versions**
 Windows 11
 Java 8 Update 271
 Minecraft 1.19
 Fabric 0.14.12
 Origins 1.19-1.6.2
 Pehkui 3.4.1+1.14.4-1.19.2
 Fabric API 0.58.0+1.19
 OriginsTweaks 1.12.1

**Comment by ChromexUnderscore** [comment]
Thank you for reporting this bug!
Unfortunately, due to private reasons I can't work on this project for the time being, but I'm trying to do so as soon as possible!
I'm sorry for any issues with game balancing that may occur...
