### ISSUE TITLE
Arachnid doesn't reset size [1.20.1]

### ISSUE THREAD

**Issue by Exokyhh** [ChromexUnderscore/OriginsTweaks#44]
**Describe the bug**
Changing origin with an Orb Of Origin (the item), if the Arachnid was previously selected (current origin), size won't reset, resulting in a smaller size for every origin chosen.

**To Reproduce**
1. Chose the Arachnid origin
2. Change Origin via item
3. Check your size, it's smaller (the same as Arachnid)

**Expected behavior**
A reset of the base default size.

**Screenshots**
![2024-05-02_20 04 43](https://github.com/ChromexUnderscore/OriginsTweaks/assets/90096585/bb448712-1b12-4c61-8351-e37d3a0e81cf)

**Versions**
originstweaks-1.15.4.jar
Origins-1.20.1-1.10.0.jar

Fabric 0.15.10

**Log**
[latest.log](https://github.com/ChromexUnderscore/OriginsTweaks/files/15192296/latest.log)

**Comment by ChromexUnderscore** [comment]
Thank you for your Bug Report!
Unfortunately, I cannot replicate the issue...
In a fresh profile with exclusively necessary mods installed (FAPI/Origins/Pehkui/OT) it works as intended.
You are also running an outdated version of OriginsTweaks; please try the latest version of OriginsTweaks, if possible.
Unfortunately, I can't maintain older builds of the mod for earlier versions of Minecraft.

**Comment by Exokyhh** [comment]
Oh, okay. So it's a weird incompatibility, mhhh, I'll try and find the mod which is causing the problem

**Comment by Exokyhh** [comment]
I'm running the most recent version on Modrinth. Where can I find the latest version?

![image](https://github.com/ChromexUnderscore/OriginsTweaks/assets/90096585/320bf15c-ebff-4a2a-9f95-1ba7822ab8cf)

**Comment by ChromexUnderscore** [comment]
> I'm running the most recent version on Modrinth. Where can I find the latest version?
> 
> Edit: I understood now what you mean ahaha, you are developing for more recent versions than 1.20.1... but I'm kinda confused, isn't 1.20.1 the most recent version for modding? 1.21 isn't out yet, and some standard versions are always required for modding, like 1.19.2, 1.18.2, 1.16.5, 1.12.2, exc.... Do people play 1.20.2? I thought everyone was developing for 1.20.1
> 
> ![image](https://private-user-images.githubusercontent.com/90096585/327573747-320bf15c-ebff-4a2a-9f95-1ba7822ab8cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODU1NjAsIm5iZiI6MTcxNjc4NTI2MCwicGF0aCI6Ii85MDA5NjU4NS8zMjc1NzM3NDctMzIwYmYxNWMtZWJmZi00YTJhLTlmOTUtMWJhNzgyMmFiOGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA0NDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNjNjZDhmMDhjYzNkMGMzYWIzOWZiNzYyZWJmYzBkN2Q1MmY3ZTc4MWI2NDQwZTkyYjg3MWU4Y2FmNDlkOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-GeOaQSvxZ9kIGNmh8px6A3jF8kiAXxWoIsqKu9Yfak)

The latest Version of Origins that has features I use is for 1.20.2.
