### ISSUE TITLE
Elytrian Wing disabler pack & custom template

### ISSUE THREAD

**Issue by PolyframeX** [ChromexUnderscore/OriginsTweaks#45]
**Type of Idea**
Ability to disable new elytra texture in config

**Describe your Idea**
Currently, it is not possible to disable the new elytra texture that is used with the mod, it would be very useful if there was a config somewhere to disable this. As some people may not like the visuals of it or it may cause conflicts with other mods.

**Comment by ChromexUnderscore** [comment]
I'm pretty sure I can make the extra texture an optional built-in texture pack, I'd have to check how fabric handles this kind of thing...
Thank you for this suggestion, I will try to implement it!

**Comment by ChromexUnderscore** [comment]
Since the Elytrian Wings use a separate texture path, disabling the textures would show a missing texture (black and pink) rather than the standard wings
I will add a built in texture pack to replace this texture pack with the standard Elytra texture, and a template on how to use a custom texture.

**Comment by ChromexUnderscore** [comment]
Implemented in v1.16.2.
An option layer for elytrians is available to pick between the vanilla and custom texture, or optionally turn off rendering of the elytra.

**Comment by offmedium** [comment]
Hello! I apologize, this is my first time on github, I just had a question about the elytrian wings.
In this thread, you said that the elytrian wings for OT use a different path than regular ones, and that it should now be possible to create your own textures for elytra wings. Me and some friends are using this mod for a server, but we are having difficulty with how to actually create a custom elytra texture. Where do we put the texture once we've made it? And, once it's made, will we have to share the file with others in order for them to see it?

Currently, the wings just disappear when we choose the "custom texture" option for the OT elytrian origin. Even if we try to load the template as a resource pack, nothing shows up. We do have some other mods in this modpack, but nothing should be affecting the OT textures AFAIK.

I'm sorry for commenting the question here, I just couldn't find any information on how to change the wings in the wiki, nor anywhere else.
