### ISSUE TITLE
integration with Origins: Dietary Delights

### ISSUE THREAD

**Issue by newtitanagle** [ChromexUnderscore/OriginsTweaks#46]
compatibility and integration with Origins: Dietary Delights https://modrinth.com/mod/origins-dietary-delights 
so people are not so restricted with food mods or mods that add food

**Comment by ChromexUnderscore** [comment]
This is a great idea!
I've been trying to do something similar myself.
I'll get in contact with the developer of this mod to ask if I'm allowed to implement this to OriginsTweaks.

**Comment by newtitanagle** [comment]
cool

**Comment by ChromexUnderscore** [comment]
Implemented in v1.16.2
