### ISSUE TITLE
Modrinth 1.20.1 arachne not getting drops when breaking blocks

### ISSUE THREAD

**Issue by Raegier** [ChromexUnderscore/OriginsTweaks#51]
**Describe the bug**
When using the arachne origin upon breaking a vanilla block nothing will drop, this persisted after reloads and only stopped after removing the mod, as far as my testing has gone all modded blocks function as expected

**To Reproduce**
Create a new world and start as the arachne origin then break any block

**Expected behavior**
receive block drops when breaking blocks

**Versions**
Windows 11, Fabric 1.20.1

**Comment by ChromexUnderscore** [comment]
Which version of OriginsTweaks are you using?

**Comment by Raegier** [comment]
Sorry for the late response. I was using origins 1.10.0 and OriginsTweaks 1.15.4

**Comment by Raegier** [comment]
So i found out that somehow its this mod causing the issue
https://modrinth.com/mod/musket-mod
